# Generated by Django 4.2.14 on 2024-08-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_in', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('assembly', models.CharField(max_length=50)),
                ('engine_capacity', models.IntegerField()),
                ('body_type', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='ads.ad')),
            ],
        ),
    ]
