# Generated by Django 4.2.14 on 2024-08-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='image',
            name='car',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='car',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='source',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='InspectionReport',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
