# Generated by Django 4.2.14 on 2024-08-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_date', models.DateField()),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('grade', models.CharField(max_length=50)),
                ('exterior_body', models.CharField(max_length=255)),
                ('engine_transmission_clutch', models.CharField(max_length=255)),
                ('suspension_steering', models.CharField(max_length=255)),
                ('interior', models.CharField(max_length=255)),
                ('ac_heater', models.CharField(max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='ads.car')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cars', models.ManyToManyField(related_name='features', to='ads.car')),
            ],
        ),
    ]
