# Generated by Django 4.2.14 on 2024-08-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_created_at_ad_last_modified_at_alter_ad_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='last_modified_at',
            new_name='modified_at',
        ),
    ]
