# Generated by Django 4.2.14 on 2024-08-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0002_remove_feature_cars_remove_image_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_in', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('assembly', models.CharField(max_length=50)),
                ('engine_capacity', models.IntegerField()),
                ('body_type', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='ads.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_date', models.DateField(blank=True, null=True)),
                ('overall_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('exterior_body', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_transmission_clutch', models.CharField(blank=True, max_length=50, null=True)),
                ('suspension_steering', models.CharField(blank=True, max_length=50, null=True)),
                ('interior', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_heater', models.CharField(blank=True, max_length=50, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.source')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cars', models.ManyToManyField(related_name='features', to='cars.car')),
            ],
        ),
    ]
