# Generated by Django 4.2.14 on 2024-08-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='external_image_url',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='uploaded_image',
        ),
        migrations.AlterField(
            model_name='car',
            name='assembly',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='registered_in',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='ac_heater',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='engine_transmission_clutch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='exterior_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='grade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='interior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='overall_rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='suspension_steering',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(),
        ),
    ]
