# Generated by Django 4.2.14 on 2024-08-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfeature',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_features', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_features', to='cars.feature'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='inspectionreport',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='cars.source'),
        ),
    ]
